#!/usr/bin/env bash
# configure server with custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'printf "Ceci n'\''est pas une page\n" > /var/www/html/404.html'
sudo sed -i '24i\  add_header X-Served-By $HOSTNAME;\n' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload
